//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadHeladeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int id { get; set; }
        public int idCliente { get; set; }
        public int idEmpleado { get; set; }
        public System.DateTime fechaPedido { get; set; }
        public string tipoPago { get; set; }
        public string estadoEntrega { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
